removed clip related
removed DEST param in make file

various default symbols location

diff --git a/unipicker b/unipicker
--- a/unipicker
+++ b/unipicker
@@ -1,25 +1,8 @@
 #!/bin/bash
 set -e
 
-should_copy=false
-
-if [ -f /etc/unipickerrc ]; then
-  source /etc/unipickerrc
-fi
-
-if [ -f "$HOME/.unipickerrc" ]; then
-  source "$HOME/.unipickerrc"
-fi
-
-case "$OSTYPE" in
-  darwin*) os_copy_command="pbcopy";;
-  linux*)  os_copy_command="xclip -selection clipboard";;
-  *)       os_copy_command="xclip -selection clipboard";;
-esac
-
-symbols_file="${UNIPICKER_SYMBOLS_FILE:-${PWD}/symbols}"
+symbols_file="${UNIPICKER_SYMBOLS_FILE}"
 select_command=${UNIPICKER_SELECT_COMMAND:-fzf}
-copy_command=${UNIPICKER_COPY_COMMAND:-${os_copy_command}}
 
 usage () {
   echo "Select unicode character by description"
@@ -28,50 +11,48 @@ usage () {
   echo ""
   echo "Arguments:"
   echo "  --command       Overrides default select command"
-  echo "  --copy-command  Override copy to clipboard command, implies --copy"
-  echo "  --copy          Copy to clipboard"
   echo "  --list          Only list the symbols, do not select or copy"
+  echo "  --symbols       Location of symbols file"
   echo ""
   echo "Variables:"
   echo ""
   echo "  UNIPICKER_SELECT_COMMAND  Command to use for selecting (= $select_command)"
-  echo "  UNIPICKER_COPY_COMMAND    Command to use for copying (= $copy_command)"
-  echo "  UNIPICKER_SYMBOLS_FILE    Location of symbols (= $symbols_file)"
+  echo "  UNIPICKER_SYMBOLS_FILE    Location of symbols (/usr/share/unipicker/symbols or ~/.local/share/unipicker/symbols or ${PWD}/symbols)"
 }
 
 while [ -n "$1" ];do
-  case "$1" in
-    --command)
-      select_command=$2
-      shift
-      ;;
-    --copy)
-      should_copy=true;;
-    --copy-command)
-      copy_command=$2
-      should_copy=true
-      shift
-      ;;
-    --symbols)
-      symbols_file=$2
-      shift
-      ;;
-    --list)
-      cat "$symbols_file"
-      exit;;
-    -h|--help)
-      usage
-      exit;;
-    *)
-      echo "Invalid argument: $1"
-      exit 1;;
-  esac
-  shift
+    case "$1" in
+        --command)
+            select_command=$2
+            shift
+            ;;
+        --symbols)
+            symbols_file=$2
+            shift
+            ;;
+        --list)
+            cat "$symbols_file"
+            exit;;
+        -h|--help)
+            usage
+            exit;;
+        *)
+            echo "Invalid argument: $1"
+            exit 1;;
+    esac
+    shift
 done
 
-letter=$(cat "$symbols_file" | eval $select_command | sed -E 's/^(.).*/\1/g')
-
-echo "$letter"
-if [ "$should_copy" = true ];then
-  echo -n "$letter" | $copy_command
+if [ -f $symbols_file ] ; then
+    if [ -f /usr/share/unipicker/symbols ]; then
+        symbols_file=/usr/share/unipicker/symbols
+    elif [ -f ~/.local/share/unipicker/symbols ]; then
+        symbols_file=~/.local/share/unipicker/symbols
+    elif [ -f ${PSW}/symbols ]; then
+        symbols_file=${PSW}/symbols
+    else
+        echo not found symbols file $symbols_file > /dev/stderr;
+        exit 1
+    fi
 fi
+cat "$symbols_file" | $select_command | sed -E 's/^(.).*/\1/g'
